### PR TITLE
feat: change ApiClient to be Send+Sync

### PR DESCRIPTION
**Pull request by xemwebe**
For some project of my own, I needed ApiClient to be Sync+Send, therefore, I made some modifications to your crate.
If you think this might be an improvement to your crate, feel free to merge it.

### CODE REVIEW

**Review by iamsauravsharma — CHANGES_REQUESTED** [review]
Looks all good except two small changes, Can you run `cargo fmt` for formatting code and follow conventional commit message specification for writing commit message

**Comment by xemwebe** [comment]
`cargo fmt` gave me some warning due to unstable feature settings only available in nightly, but I believe they had not impact for the changes I made.

**Review by iamsauravsharma — APPROVED** [review]

**Comment by iamsauravsharma** [comment]
bors merge

**Comment by iamsauravsharma** [comment]
PR released with version `0.7.0`

**Comment by xemwebe** [comment]
Thanks!

**Pull request merged**
